# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - main
      - '*'
  paths:
    include:
      - src/*

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  projectName: $(System.TeamProject)
  repositoryName: $(Build.Repository.Name)

steps:
- script: |
    echo "Project Name: $(projectName)"
    echo "Repository Name: $(repositoryName)"
  displayName: 'Display Project and Repository Names'

- script: |
    echo "Collection URI: $(System.CollectionUri)"
    # Extract the organization name from the collection URI
    organizationName=$(echo $(System.CollectionUri) | awk -F'/' '{print $4}')
    echo "Organization Name: $organizationName"
  displayName: 'Extract and Display Organization Name'
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQube Server-python-example'
    scannerMode: 'cli'
    cliScannerVersion: '6.2.1.4610'
    configMode: 'file'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.verbose=true
      sonar.projectKey=onboarding-examples_python-example
      sonar.projectName=onboarding-examples_python-example
      sonar.sources=src/

- task: SonarQubeAnalyze@7
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'
