# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/*

pool:
  vmImage: ubuntu-latest

variables:
  projectName: $(System.TeamProject)
  repositoryName: $(Build.Repository.Name)

resources:
  repositories:
    - repository: templates
      type: git
      name: pipeline-templates/pipeline-templates

steps:
  - script: |
      echo "Project Name: $(projectName)"
      echo "Repository Name: $(repositoryName)"
    displayName: 'Display Project and Repository Names'

  - script: |
      echo "Collection URI: $(System.CollectionUri)"
      # Extract the organization name from the collection URI
      organizationName=$(echo $(System.CollectionUri) | awk -F'/' '{print $4}')
      echo "Organization Name: $organizationName"
    displayName: 'Extract and Display Organization Name'
    
  - template: sonarqube-server.yml@templates
    parameters:
      projectKey: 'azure-pipeline-template-test'
      projectName: 'azure-pipeline-template-test'
      SonarQubeServiceConnection: 'SonarQube Server-$(System.TeamProject)'
  
